language: go

go:
        - "1.13"
        - master

branches:
        only: master

before_install:
        - go get -t -v ./...
        - go get -v github.com/mitchellh/gox
        - go get -v github.com/tcnksm/ghr

script:
        - gox -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"
        - ghr --username syui --token $GITHUB_TOKEN --replace --debug 0.2.3 dist/
